version: '3.7'

services:
   product-service:
      image: product-service:1.0
      ports:
         - "9090:9090"
      depends_on:
         - rabbitmq
      environment:
         RABBIT_URI: amqp://guest:guest@rabbitmq:5672
         SPRING_RABBITMQ_HOST: rabbitmq
      networks:
         - market-network
   
   viewed-product-service:
      image: viewed-product-service:1.0
      ports:
         - "9091:9091"
      depends_on:
         - redis-server
         - mysqldb
         - rabbitmq
      environment:
         RABBIT_URI: amqp://guest:guest@rabbitmq:5672
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/market
         SPRING_REDIS_HOST: redis
         SPRING_REDIS_PORT: 6379
      networks:
         - market-network

   rabbitmq:
      image: rabbitmq:management
      ports:
      - 5672:5672
      - 15672:15672
      networks:
         - market-network
      
   redis-server:
     restart: always
     image: 'redis'
     container_name: redis
     hostname: redis
     ports:
       - "6379:6379"
     networks:
       - market-network
       
   mysqldb:
      image: mysql:latest
#      image: 'mysqldb'
      hostname: mysqldb
      ports:
         - "3306:3306"
      environment:
#         - MYSQL_USER=root
         - MYSQL_PASSWORD=password
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=market
      restart: always
#         - TZ=Asia/Seoul
#      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+09:00']
      networks:
         - market-network
      
      
networks:
   market-network:
