version: '3.7'

services:
   product-service:
      image: product-service:1.0
      ports:
         - "9090:9090"
      depends_on:
         - rabbitmq
         - mysqldb
      environment:
         RABBIT_URI: amqp://guest:guest@rabbitmq:5672
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/market?autoReconnect=true&useSSL=false
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: password
      networks:
         - market-network
   
   viewed-product-service:
      image: viewed-product-service:1.0
      ports:
         - "9091:9091"
      depends_on:
         - redis-server
         - mysqldb
         - rabbitmq
      environment:
         RABBIT_URI: amqp://guest:guest@rabbitmq:5672
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/market?autoReconnect=true&useSSL=false
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: password
         APPLICATION_REDIS_HOST: redis
         APPLICATION_REDIS_PORT: 6379
      networks:
         - market-network

   rabbitmq:
      image: rabbitmq:management
      ports:
      - 5672:5672
      - 15672:15672
      networks:
         - market-network
      
   redis-server:
     restart: always
     image: 'redis'
     container_name: redis
     hostname: redis
     ports:
       - "6379:6379"
     networks:
       - market-network
       
   mysqldb:
      image: mysql:5.7
      hostname: mysqldb
      container_name: mysqldb
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=market
         - MYSQL_PASSWORD=password
      restart: always
      networks:
         - market-network
      
      
networks:
   market-network:
